# Generated by Django 4.0.4 on 2022-07-11 13:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_data_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_post',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 11, 13, 56, 50, 293686, tzinfo=utc)),
        ),
    ]
